Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  Max: 26

Metrics/MethodLength:
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Exclude:
    - app/models/application_record.rb

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

AllCops:
  NewCops: enable
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - vendor/**/*
