Layout/LineLength:
  Max: 100

Lint/AmbiguousBlockAssociation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Max: 26

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Exclude:
    - app/models/application_record.rb

Style/HashSyntax:
  EnforcedStyle: 'ruby19'

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

AllCops:
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - vendor/**/*
