Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Max: 26

Metrics/BlockLength:
  Max: 26

Metrics/ClassLength:
  Max: 102

Metrics/MethodLength:
  Max: 16

Style/Documentation:
  Exclude:
    - app/models/application_record.rb

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

AllCops:
  NewCops: enable
  Exclude:
    - config.ru
    - Gemfile
    - Rakefile
    - bin/*
    - config/**/*
    - db/schema.rb
    - db/seeds.rb
    - db/migrate/*
    - spec/spec_helper.rb
    - spec/rails_helper.rb
    - vendor/**/*

require:
  - rubocop-rails
  - rubocop-rspec

Rails/HasManyOrHasOneDependent:
  Exclude:
    - app/models/pseudo_graph_pattern.rb

Rails/InverseOf:
  Exclude:
    - app/models/pseudo_graph_pattern.rb

RSpec/ExampleLength:
  Max: 10

RSpec/NamedSubject:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 2

RSpec/NoExpectationExample:
  Enabled: false