openapi: 3.0.0
info:
  version: 1.0.0
  title: Chat GPT Plugin API
paths:
  /chat_gpt_plugin:
    post:
      operationId: createChatGptPlugin
      summary: Search linked open data by natural language query. The result has to be rendered as [Result in LODQA](lodqaLink).
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
          description: The query string for search.
        - in: query
          name: target
          schema:
            type: string
          description: The name of the SPARQL endpoint to search.
      responses:
        '200':
          description: OK!
          content:
            application/json:
              schema:
                type: object
                properties:
                  lodqaLink:
                    type: string
                    description: The URL to LODQA.