openapi: 3.0.0
info:
  version: 1.0.0
  title: Chat GPT Plugin API
paths:
  /chat_gpt_plugin:
    post:
      summary: Search linked open data by natural language query. The result has to be rendered as [Result in LODQA](lodqaLink).
      operationId: createChatGptPlugin
      requestBody:
        description: query to search
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                query:
                  type: string
                  description: The query string for search.
      responses:
        '200':
          description: OK!
          content:
            application/json:
              schema:
                type: object
                properties:
                  lodqaLink:
                    type: string
                    description: The URL to LODQA.
